### PR TITLE
Adjusted UI for login/signup page

### PR DESCRIPTION
**Pull request by jennkim0409**
Adjusted the frontend design of the Login/Signup page to match the Figma layout. 
https://www.figma.com/file/mbfxbriwZn43udOsryBTbE/CS-130-Group-Project?type=design&node-id=0-1&mode=design&t=PKuqtkWN7B8KBXVu-0

Also included storage of logging in information to localStorage.

### CODE REVIEW

**Review by kimcharlene — CHANGES_REQUESTED** [review]
1. was wondering if you wanted to add any other fields to signing up? (i.e. name)
2. also wondering if sign-up with email is necessary. (if we have username already)

if both 1, 2 are no, we could probably just have one screen with username and password field, and two buttons with either "login" or "signup", rather than it switching pages?

**Comment by jennkim0409** [comment]
> 1. was wondering if you wanted to add any other fields to signing up? (i.e. name)
> 2. also wondering if sign-up with email is necessary. (if we have username already)
> 
> if both 1, 2 are no, we could probably just have one screen with username and password field, and two buttons with either "login" or "signup", rather than it switching pages?

Fair points. I’ll bring it up with backend first and will likely adjust the email entry to be a name entry instead. And as for your last question, it actually never switches pages. The elements being displayed to the user just differs (ie no email div for login and no forgot password div for sign up) depending on the current action

**Comment by kimcharlene** [comment]
sounds good, you could also consider having the name field reside in the page you collect user’s preferences start

maybe that page could also be the default that comes up when someone presses “Account” (to edit name and preferences)

**Comment by jennkim0409** [comment]
Yup yup! That was what I was thinking too

**Comment by kimcharlene** [comment]
cool! then we could probably just have the username/password fields and “login” signup” buttons on the first page (and name and preferences on next, if they signup for first time)

**Comment by jennkim0409** [comment]
Okie sounds good! Then if that second sign up page is the same as the account page, should I still provide the option to change password? Or do you think it’s not necessary since we have “forgot password”

**Pull request merged**
