### PR TITLE
Update or View Existing Pins

### PR DESCRIPTION
**Pull request by jennkim0409**
Wrote Frontend code to make existing Pins on Board clickable and also provide an option for user to update information.

### CODE REVIEW

**Comment by kharris29** [comment]
the X icon here was a little confusing for me - at first I thought it was deleting the pin as a whole, but I realize it's just removing the image. could you alter the icon or add little text that's something like "replace image"? :)

Screenshot 2024-03-04 at 12 16 39 PM

**Comment by kharris29** [comment]
otherwise looks great to me! thanks jenn :)

**Comment by kharris29** [comment]
oh also, do you think it would be a good idea to have a save button at the bottom of the 'edit pin' pop-ups? so that the settings aren't immediately adjusted and can be reverted if user wants to go back?

**Comment by kharris29** [comment]
> > the X icon here was a little confusing for me - at first I thought it was deleting the pin as a whole, but I realize it's just removing the image. could you alter the icon or add little text that's something like "replace image"? :)
> > Screenshot 2024-03-04 at 12 16 39 PM
> 
> Okie! I updated the code to have a tooltip that says "Remove Image" when a user hovers over the icon :) Screenshot 2024-03-04 at 1 55 54 PM

this is perfect! thank you

**Comment by jennkim0409** [comment]
> oh also, do you think it would be a good idea to have a save button at the bottom of the 'edit pin' pop-ups? so that the settings aren't immediately adjusted and can be reverted if user wants to go back?

there’s an update button at the top corner of edit pins! if a user doesn’t click on that, then the updates aren’t saved if that’s what you mean :)

**Comment by kharris29** [comment]
thanks for addressing comments! looks great

**Pull request merged**
